export type Publication = {
  faculty: string
  title: string
}

export const publishedPapers: Publication[] = [
  { faculty: 'Dinesh Kumar Sharma', title: 'Green Corrosion Inhibition of Mild Steel in Acidic Media: Electrochemical Behavior and Theoretical Studies of Zingiber Mioga Essential Oil' },
  { faculty: 'Pooja Kapoor', title: 'Fake Reviews as Dark Patterns: A Nudge Theory Perspective Using the SOR Framework' },
  { faculty: 'Meenakshi Gupta', title: 'Development of Wireless Communication Technologies from 1G to Sustainable 6G' },
  { faculty: 'Rashi Banerji & Animesh Singh', title: 'Unlocking the Nexus: Exploring Happiness at Work, Workplace Spirituality, and OCB in Indian Private Sector Banks' },
  { faculty: 'Priti Gupta', title: 'Tailored Conducting Polymers as Energy Storage Devices' },
  { faculty: 'Akanksha Kathuria, Neeraj Chopra & Animesh Singh', title: 'Exploring the Role of Digital Financial Literacy in Promoting Sustainable Digital Financial Inclusion' },
  { faculty: 'Akanchha Singh', title: 'Service Quality and Its Effect on Customer Satisfaction in Digital Banking' },
  { faculty: 'K. Deepa', title: 'PUF based Secure Authentication System for Embedded Cyber-Physical Systems' },
  { faculty: 'Ekta Rawat', title: 'An on-board Journey from Conventional to Novel Biomarkers for Detection and Monitoring of Alzheimer\'s Disease' },
  { faculty: 'Esha Khanna', title: 'RSTS: A Novel Approach to Pre-processing for Alzheimer\'s Detection Using MRI' },
  { faculty: 'Sandeep Kumar & Jitendra Pal Singh', title: 'Study of Ferrites Using X-Ray Photoelectron Spectroscopy' },
  { faculty: 'Sonal Trivedi', title: 'Rural Futures: Innovation, Resilience, and Sustainable Development' },
  { faculty: 'Dinesh Kumar Sharma', title: 'Low-Carbon Materials: Transportation and Automotive Applications' },
  { faculty: 'M. Javed Idrisi', title: 'Dynamics of the Radiating Sitnikov Five-Body Problem with Poynting-Robertson Drag' },
  { faculty: 'Priyanka Bansal', title: 'Performance Assessment of Loop-Cutting 10T SRAM Cell For High Performance Computation' },
  { faculty: 'Jitendra Pal Singh & Jai Parkash', title: 'Influence of Sintering Duration on Structural, Optical and Magnetic Behaviour of Cobalt Ferrite' },
  { faculty: 'M. Javed Idrisi', title: 'A Nonlinear Mathematical Model for AI Integration and Resource Dynamics in Healthcare' },
  { faculty: 'Teena Hassija', title: 'Sustainable Finance in India: A Review of ESG Investment Instruments, Policies, and Challenges' },
  { faculty: 'Bhim Singh', title: 'Enhancement of Mechanical Properties in Hemp Fiber-Reinforced Epoxy Composites using Graphene nanoplatelets' },
  { faculty: 'Deepti Maikhuri & Anshuman Sahai', title: 'Difference frequency generation in CdSe quantum dots: the effect of conduction band nonparabolicity' },
  { faculty: 'Kavita Singh', title: 'Optimal Frequency Control in Renewable-Dominated Multi-Microgrids via Salp Swarm Algorithm' },
  { faculty: 'Chaitali Wadhwa & Shaharyar Asaf Khan', title: 'Levelling The Playing Field: Leveraging AI-Driven Recruitment to Mitigate Motherhood Discrimination' },
  { faculty: 'Sonal Trivedi', title: 'Agripreneurship, Digital Inclusion and Sustainability: Rural Innovation and Growth in the Global South' },
  { faculty: 'Mrinal Pandey & Mamta Arora', title: 'Deep Learning Framework Pertaining to Peach Leaf Disease Classification' },
  { faculty: 'Mrinal Pandey', title: 'Optimized Fractal Fusion Driven Deep Neural Network for Disease Detection and Classification in Plant Leaves' },
  { faculty: 'Vinayak Vandan Pathak', title: 'Assessing Climate Change Impacts on Heat Waves and Heat Index: a Case Study of Uttar Pradesh, India' },
  { faculty: 'S.K. Bose & Deepak Bansal', title: 'Sustainable Governance and Cooperative Federalism: Fostering Innovation in India\'s Entrepreneurial Ecosystem' },
  { faculty: 'Shaharyar Asaf Khan', title: 'Role Of AI Technologies In Advancing India\'s Forest Conservation and Wildlife Protection Frameworks' },
  { faculty: 'Shaharyar Asaf Khan', title: 'Alternative Dispute Resolution in Family Law and the Emerging Scope of Online Dispute Resolution' },
  { faculty: 'Yogita Sharma', title: 'A Comprehensive Analysis in the Dynamic Landscape of Healthcare Start-Ups Using Neural Networks' },
  { faculty: 'Mamta Arora', title: 'Early Tomato Leaf Disease Prediction Using Deep Learning Techniques' },
  { faculty: 'Dipali Bansal', title: 'Evaluating the Impact of Fine-Tuning on Deep Neural Networks for Skin Cancer Detection' },
  { faculty: 'Varun Yadav', title: 'Low-Leakage Techniques Comparison For Static Random Access Memory Bit-Cell' },
  { faculty: 'Parneeta Dhaliwal', title: 'Multiclass Classification of Retinal Diseases Using Transfer Learning' },
  { faculty: 'Nazish Ahmad Shamsi', title: 'Nonlinear Dynamics of Carbon Emissions and Renewable Energy: A Mathematical Model for Climate Sustainability' },
  { faculty: 'Pragati Chauhan', title: 'The Conscious Leadership Paradigm: A Necessity for Business Schools' },
  { faculty: 'Piyush Charan', title: 'Secure and Robust WSN Architecture: Detection of Malicious Nodes and Impact Assessment on Link Stability' },
  { faculty: 'Shruti Vashist', title: 'Notch Filter based Modified CSOGI-PLL to Improve Dynamics of Single Phase Grid Connected Solar PV Array' },
  { faculty: 'Dinesh Kumar Sharma & Gurpreet Singh Matharou', title: 'Carbon Sequestration: A Technological Aspect and Importance' },
  { faculty: 'Ekta Rawat', title: 'Role of nanoparticles in bladder cancer management' },
  { faculty: 'Shruti Vashist', title: 'Performance Enhancement of Mixed RF-FSO Networks via UAV Positioning and Opportunistic User Scheduling' },
  { faculty: 'Shweta Goel', title: 'Modelling Intention and Trust in AI-Based Digital Payments for Sustainable Rural Entrepreneurship' },
  { faculty: 'Deepti Maikhuri & Anshuman Sahai', title: 'THG Enhancement in CdSe Quantum Dots: Interplay of Surrounding Matrix and Quantum Confinement' },
  { faculty: 'Neha Chaudhary', title: 'AI-optimised Energy Efficient Communication protocol for WSNs' },
  { faculty: 'Mandeep Bhadana, Prashant Bhardwaj & Pradeep Kumar Mouria', title: 'Parametric Optimization of RA-GMAW Welded Joints of Dissimilar AA6061/AA7075 Welded Joints' },
  { faculty: 'S.K. Bose, Deepak Bansal, Yogita Sharma & Aditi Chaudhary', title: 'Bias, Fairness and the Machine in the Sustainable Digital Ecosystem' },
  { faculty: 'Piyush Charan', title: 'Performance Analysis of Double Material Cylindrical Surrounding Gate Mosfet' },
  { faculty: 'Sonal Trivedi', title: 'Green Policies and Augmented Reality in InsurTech: Catalysts for Sustainability and Innovation' },
  { faculty: 'Mrinal Pandey', title: 'Ensemble Classification of Breast Cancer Using Texture and Color Features' },
  { faculty: 'M. Javed Idrisi', title: 'The Elliptic Sitnikov Five-Body Problem' },
  { faculty: 'Niharika Thakur', title: 'Image-Based Malware Classification Using DCGAN-Augmented Data and a CNN-Transformer Hybrid Model' },
  { faculty: 'Abhishek Saxena', title: 'A Grid Search Ensemble Framework for Analyzing Agricultural Productivity Based on Agro-Climatic Factors' },
  { faculty: 'Vinayak Vandan Pathak & Sangita Banga', title: 'RSM-CCD-Based Optimization of D-Limonene Extraction and its Catalytic Transformation into Chitosan Fabricated Schiff base Chemosensor' },
  { faculty: 'Sandeep Kumar & Jai Parkash', title: 'Structural and Up-conversion Luminescence Properties of LiGa5-x(YbRCr)xO8 Ceramics' },
  { faculty: 'Mamta Arora', title: 'An ML-Driven Framework for Parkinson\'s Disease Identification from Voice Data' },
  { faculty: 'Parneeta Dhaliwal', title: 'BirthChain: A Blockchain Platform for Birth Certificates' },
  { faculty: 'Prinima Gupta', title: 'Automated Detection of Lesions in Brain MRI Scans Using Convolutional Neural Networks' },
  { faculty: 'Prinima Gupta', title: 'Enhanced UAV Target Recognition via YOLOv8-SR with Optimized Super-resolution and Hyperparameters' },
  { faculty: 'Vinayak Vandan Pathak & Sangita Banga', title: 'Environment Friendly Colorimetric Schiff Base Chemosensor for Detection of Fe+3 Ions' },
  { faculty: 'Arpit Sand', title: 'Development of UV-Resistant Chitosan/Starch Biofilms Reinforced with Chitosan Nanoparticles for Sustainable Packaging' },
  { faculty: 'Urmila Pilania & Manoj Kumar', title: 'Unveiling the Art of Steganography: A Modern Approach' },
  { faculty: 'S.K. Bose, Deepak Bansal & Akanshi Taneja', title: 'AI-Driven Dispute Resolution as a Sustainable Institutional Innovation In India\'s Construction Entrepreneurship Ecosystem' },
  { faculty: 'Aaratrika Pandey', title: 'Beyond Symbolic Compliance' },
  { faculty: 'Aaratrika Pandey', title: 'Conceptualizing the Anatomy of Green Criminology in South Asia' },
  { faculty: 'Aaratrika Pandey', title: 'Copyright Exceptions and Limitations for AI Innovation: A Need for Tailored Reform?' },
  { faculty: 'Gurpreet Kaur', title: 'Flash Sales and FOMO: Evidence from Gadget Impulse Buying' },
  { faculty: 'Advin Masih', title: 'Quasi Bi-Slant Submanifold of Trans-Sasakian Manifold' },
  { faculty: 'Moditma & Jitendra Pal Singh', title: 'Impact of Heating/Cooling Rate on the Post-Deposition Annealing of LLZO thin films' },
  { faculty: 'Sachin Lakra', title: 'Advancing Cloud Load Balancing: An Energy-Aware Model using a Hybrid Genetic and Nature-Inspired Algorithm' },
  { faculty: 'Chandni Magoo', title: 'Synthetic Image Differentiation Using Multimodal Feature Fusion via Clustering' },
  { faculty: 'Joginder Singh', title: 'A Comprehensive Review on the Processing, Microstructure, Mechanical, and Tribological Properties of Aluminum Matrix Composites' },
  { faculty: 'Ananna Bardhan & Dinesh Kumar Sharma', title: 'Variabilities in Ionospheric Parameters Induced by the 27 Days Solar Rotation' },
  { faculty: 'Esha Khanna & Tamanna Sachdeva', title: 'Tree-Based Machine Learning Algorithms for Alzheimer\'s Disease Prediction' },
  { faculty: 'Chandni Magoo', title: 'Deep Learning Based Burned Wound Severity Prediction Multimodal' },
  { faculty: 'Chandni Magoo', title: 'Comparative Analysis of Various Neural Network For Galaxies Classification' },
  { faculty: 'Chandni Magoo', title: 'A Deep Learning-Based Sign Language Recognition System Using Convolutional Neural Networks' },
  { faculty: 'Animesh Singh', title: 'The Mediating Role of Organisational Commitment in the Relationship of Emotional Intelligence and OCB' },
  { faculty: 'Richa Adlakha', title: 'Comparison of an AI-Based Controller for a Positive Output Superlift DC-DC Converter' },
  { faculty: 'S.K. Bose, Deepak Bansal & Akanshi Taneja', title: 'Evaluating Faculty Perspectives on the Science of Teaching Accounting and Law in the Age of AI' },
  { faculty: 'Mandeep Bhadana, Prashant Bhardwaj & Pradeep Kumar Mouria', title: 'Optimization of Process Parameters of RA-GMAW Welded Joints of Dissimilar Aluminium Alloys' },
  { faculty: 'Dinesh Kumar Sharma', title: 'Comprehensive Study of Garlic Peel Extract Coating against Mild Steel Corrosion in Saline Medium' },
  { faculty: 'Sudhish Kumar Shukla', title: 'Investigating the Effects of Carbonate Additives on Zn-Air Battery' },
  { faculty: 'Sanjay Singh & Deepti Thakral', title: 'A Comprehensive Study for NBA Game Player Position Prediction Using Feature Analysis and Machine Learning' },
  { faculty: 'Vani Kataria', title: 'Secularism in India and South Africa: A Comparative Study' },
  { faculty: 'Akanksha Kathuria & Neeraj Chopra', title: 'AI-Driven Personalization in Cloud-Powered Fashion: E-Commerce Customer Experience' },
  { faculty: 'Aditi Chaudhary', title: 'Cybercrime Investigation: Modern Trends, Challenges, and the Role of Digital Evidence' },
  { faculty: 'Animesh Singh', title: 'Validation of A Sustainable HRM Practices Scale And Employee Satisfaction In The Automobile Sector' },
  { faculty: 'Rashee Singh', title: 'Learner-Driven Methodology for Nurturing Collaborative Autonomy in Teacher Education: An Indian Context' },
  { faculty: 'Animesh Singh', title: 'The Moderating Effect Of Age, Gender, And Experience In The Impact Of Emotional Intelligence on OCB' },
  { faculty: 'Meena Chaudhary, Narender Gautam & Gunjan Chandwani', title: 'A Machine Learning Framework for Credit Card Fraud Detection: Balancing Performance on Skewed Datasets' },
  { faculty: 'Rimple Manchanda', title: 'The Role of Service Robots in Enhancing Customer Experience and Satisfaction in the Hospitality Industry' },
  { faculty: 'M. Javed Idrisi', title: 'Dynamics of the Elliptic Sitnikov Problem under Kite Configuration' },
  { faculty: 'M. Javed Idrisi', title: 'Mathematical Insights into Triangular Configurations of the Sitnikov Four-Body Dynamics' },
  { faculty: 'M. Javed Idrisi', title: 'Stability, Bifurcations, and Chaos in a radiating Oblate Concentric Sitnikov System' },
  { faculty: 'Shiv Kumar Dixit', title: 'Enhanced Performance of Lead-Free Tandem Solar Cells with CsSnCl Perovskites: 44% Power Conversion Efficiency' },
  { faculty: 'Rashi Banerji', title: 'Navigating Cybersecurity Threats and Strategies in Mobile Wallet Adoption: A User-Centric Approach' },
  { faculty: 'Dinesh Kumar Sharma', title: 'Synthesis of Ethanol Extract of Rose Petal and its Coating on Mild Steel for Corrosion Prevention' },
  { faculty: 'Savita Sharma', title: 'Bringing Constructivism in Classrooms through Technology Integration in light of NEP 2020' },
  { faculty: 'Yamini Atreya', title: 'Social Justice and Artificial Intelligence: Addressing Bias and Promoting Fairness in the EU, Australia, and India' },
  { faculty: 'Meenal Rawat, Arvinder Kaur & Eram Aziz', title: 'Strengthening Industry-Academia Partnership in Agriculture: Role of Incubation Centres' },
  { faculty: 'Jai Prakash', title: 'Structural, Dielectric, and Magnetic Properties of Bi0.9-xHoxSr0.10FeO3' },
  { faculty: 'Shruti Vashist', title: 'Natural Language Processing Perspectives on Emerging Telecommunication Networks' },
  { faculty: 'Jimmy Mehta', title: 'Unlocking Industrial Waste: Opportunities, Challenges, and Future Prospects' },
  { faculty: 'Jimmy Mehta', title: 'Composite Materials: Pioneering Sustainable Development through Energy Efficiency and Emission Reduction' },
  { faculty: 'Ekta Rawat', title: 'Nanoparticle-loaded Microneedles as Advanced Transdermal Systems for Skin Cancer Management' },
  { faculty: 'Neelu Chaudhary', title: 'A Survey on Machine Learning based Advanced Persistent Threat Detection Techniques' },
  { faculty: 'Dipali Bansal, Manoj Kumar & Urmila Pilania', title: 'Potato Leaf Disease Prediction Using Machine Learning for Sustainable Agriculture' },
  { faculty: 'Dipali Bansal, Manoj Kumar & Urmila Pilania', title: 'Sentiment Analysis for Twitter Tweets Using Machine Learning Approach' },
  { faculty: 'Urmila Pilania', title: 'Weather Forecasting Using CNN and Image Streams' },
  { faculty: 'Urmila Pilania', title: 'Real Time Wheat Crop Disease Detection Using CNN' },
  { faculty: 'Shalu', title: 'TITAN: Logarithm-Based Trust-aware Integrated Technique for Robust Anomaly Neutralization in Industrial WSNs' },
  { faculty: 'Arushi M. Mehta', title: 'Legal Dimensions of Environmental Governance in Merger and Acquisition Transactions: India and Beyond' },
  { faculty: 'Ekta Rawat', title: 'Alginate-Driven Nanotherapeutics in Liver Cancer: Design, Applications, and Future Perspectives' },
  { faculty: 'Urmila Pilania, Manoj Kumar & Sanjay Singh', title: 'Quantum Computing: Principles, Applications, and AI-Driven Innovations' },
  { faculty: 'Punam Rattan', title: 'Feature Selection for Fraud Detection: Improving Machine Learning Capabilities on Portable Wallet' },
  { faculty: 'Punam Rattan', title: 'Integrated Topic Modeling and Feature Engineering for High-accuracy Sentiment Classification in Consumer Reviews' },
  { faculty: 'Punam Rattan', title: 'Deep Learning-Assisted Early Detection of Skin Cancer from Dermoscopic Images in Underserved Clinical Settings' },
  { faculty: 'Vijay Kumar Gill, Shiv Kumar Dixit & Shruti Vashist', title: 'Effect of Different Hole Transport Layers on the Performance of Lead Free CsGeI3 based Perovskite Solar Cell' },
  { faculty: 'M. Javed Idrisi', title: 'Albedo-Induced Perturbation in the Sitnikov Three-Body Problem' },
  { faculty: 'Bhawna Singla', title: 'Fuzzy Analysis in Ophthalmology' },
  { faculty: 'Sudhish Kumar Shukla', title: 'Enhancement of Corrosion Resistance on Zinc Anode in Alkaline Environment through Electroplating Methods' },
  { faculty: 'Sudhish Kumar Shukla', title: 'Synthesis of Ethanolic Extract of Buddhist Pine Leaves and its Deposition on Copper\'s Surface for Corrosion Prevention' },
  { faculty: 'Sudhish Kumar Shukla', title: 'Sustainable Zinc-Air Batteries: Advances, Challenges and Opportunities' },
  { faculty: 'Abhishek Saxena', title: 'Predictive Modelling Of Clean Water Supply In Riau Province: A Deep Learning Approach' },
  { faculty: 'Abhishek Saxena', title: 'Extractive Clinical Notes Summarization using Single Machine Learning, Ensemble, and Stacking Approaches' },
  { faculty: 'Gianender Kajal', title: 'Optimization of Process Parameters in Single Point Incremental Forming of Ti-6Al-4V Alloy Using the Taguchi Approach' },
  { faculty: 'Ekta Rawat', title: 'Harnessing 5-Fluorouracil-Loaded Chitosan Nanoparticles for Targeted Colon Cancer Therapy' },
  { faculty: 'Awwab Mohammad', title: 'Context-Embedding in Natural Language for Keener Chatbot Responses' },
  { faculty: 'Awwab Mohammad', title: 'Enhancing Cloud Data Security against Quantum Threats Using E91 QRD AND Lattice-Based Encryption' },
  { faculty: 'Awwab Mohammad', title: 'Deep Learning-Based Cancer Diagnosis Using a Bluefin Trevally-Optimized Convolutional Neural Network' },
  { faculty: 'Akanchha Singh', title: 'Human Resource and the Happiness: Performance Link' },
  { faculty: 'Aparna Vyas', title: 'Some Coupled Fixed Point Results under Contraction Conditions Using Rational Expression in Dislocated Quasi b-Metric Space' },
  { faculty: 'Shalu', title: 'OrganBlock: A Kidney Searching and Tracking Blockchain System' },
  { faculty: 'Akhilesh Kumar Dwivedi', title: 'Shadows of Sundarbans: Unmasking Class Conflict in Bhoma' },
  { faculty: 'Bhanu Pratap Chaudhary', title: 'Analysis of CNN-LSTM assisted RIS Cooperative NOMA System' },
  { faculty: 'Monika Lamba', title: 'Optimized Fraud Detection in Credit Cards Using ML and EJaya Algorithm' },
  { faculty: 'Monika Lamba', title: 'CPDCNN: Classification of Plant Disease using Convolutional Neural Network' },
  { faculty: 'Asha Verma, Ruchi Lal & Superna Venaik', title: 'Cyber adjudication in the age of Artificial Intelligence – A Conflict of Jurisdiction' },
  { faculty: 'Deepak Bansal & S.K. Bose', title: 'Governing the digital age: Ethical Principles, Transparency, Accountability, and Human Oversight in IT Law' },
  { faculty: 'Manpreet Kaur', title: 'Efficient Real-Time Object Detection for Indoor Navigation Using Dual YOLO-SSD Networks and MobileNet Backbone' },
  { faculty: 'Manpreet Kaur', title: 'Palm2Precision: Anemia Detection through Palm Images' },
  { faculty: 'Chandni Magoo', title: 'Multimodal Deep Learning Framework for Skin Disease Classification and Severity Assessment' },
  { faculty: 'Aaratrika Pandey', title: 'Disparity of Policy and Field Reality at Areas Under Armed-Conflict in Relation to Gender-Based Violence Against Women' },
  { faculty: 'Urmila Pilania, Manoj Kumar & Sanjay Singh', title: 'Advanced Information Retrieval System: Theoretical and Experimental Perspective' },
  { faculty: 'Urmila Pilania', title: 'A Parallel Deep Ensemble for Robust Automated Classification of Brain Tumors in MRI' },
  { faculty: 'Chaitali Wadhwa & Shaharyar Asaf Khan', title: 'Motherhood and the right to Education: Harmonising Statutory Entitlements and Institutional Practice' },
  { faculty: 'Gurpreet Singh Matharou', title: 'Multi-Response Optimization of EDM Parameters for Aerospace-Grade Al6063-SiC-B4C Hybrid Metal Matrix Composites' },
  { faculty: 'Monika Lamba', title: 'Multimodal Data Fusion in Healthcare: AI Approaches for Precision Diagnosis' },
  { faculty: 'Shalu', title: 'Beyond Vision - An Artificial Intelligence Enabled Voice-Controlled Messaging Platform for the Blind' },
  { faculty: 'Asha Verma', title: 'Victim-Centric Criminal Justice under BNSS, 2023: A Comparative Study with erstwhile Cr.PC, 1973' },
  { faculty: 'Asha Verma', title: 'Victim Compensation Schemes: A Comparative Study of India, USA and UK' },
  { faculty: 'M. Javed Idrisi & Nazish Ahmad Shamsi', title: 'Modeling the Dynamic Interplay between Student Creativity and Gen-AI' },
  { faculty: 'M. Javed Idrisi & Advin Masih', title: 'Dynamics of an Infinitesimal mass near Equilibrium Points in a Radiating Heterogeneous Binary System' },
  { faculty: 'Roopa Rani & Sudhish Kumar Shukla', title: 'Synthesis and characterization techniques for ionic polymers' },
  { faculty: 'Rimple Manchanda', title: 'Empowering Women through Gig Work: Substantiating Maslow\'s Hierarchy of Needs through Phenomenology' },
  { faculty: 'Priyanka Bansal', title: 'Textile analysis for wearable antenna' },
  { faculty: 'Teena Hassija', title: 'Customer Perceptions of AI-Driven Health Insurance Services and Their Impact on Insurance Purchase Intentions' },
  { faculty: 'Gurpreet Singh Matharou', title: 'Optimization of super-twisting sliding mode control for a two-DOF robotic manipulator using metaheuristic algorithms' },
  { faculty: 'Richa Adlakha', title: 'Leveraging Digital Learning Environments and Predictive Analytics to Develop Adaptive Early Warning Systems' },
  { faculty: 'Gianender Kajal', title: 'Microstructural and Tribological Analysis of T4-Treated AI6061-ZrB2 Composites Fabricated by Stir Casting' },
  { faculty: 'Superna Venaik', title: 'Integrating AI in the Criminal Justice System for Prevention of Crime: A Holistic Approach' },
]

export const acceptedPapers: Publication[] = [
  { faculty: 'Manpreet Kaur', title: 'A Context-Aware Legal Assistant Using Intent Classification and Retrieval-Augmented Generation' },
  { faculty: 'Manpreet Kaur', title: 'Conjunctival Imaging based deep learning framework for Automated Anemia Screening' },
  { faculty: 'Akanchha Singh', title: 'Human Resource and the Happiness: Performance Link' },
  { faculty: 'Akanksha Kathuria', title: 'Cloud-Native AI for Inquiry-Based Learning: Automating Intelligence and Empowering Student Exploration' },
  { faculty: 'Shagun Chahal', title: 'Gig Workers in Q-Commerce: Workforce dynamics, Welfare Measures and Policy Imperatives' },
  { faculty: 'Piyush Charan', title: 'Performance Comparison of CNN and Random Forest Models for Intrusion Detection in IEEE 802.11-Based WSNs' },
  { faculty: 'Gurpreet Singh Matharou', title: 'Parametric Studies and Future Prospects of Drilling Electrochemical Spark Machining process: A Comprehensive Review' },
  { faculty: 'Nitika', title: 'Dual Path Transformer Diffusion Framework (DP-TDF) for Reliable Industrial Process Modelling and Prediction' },
  { faculty: 'Gunjan Chandwani, Monika Goyal & Dev Dixit', title: 'Federated Multimodal Deep Learning for Plant Disease Detection using Leaf Images and Environmental Sensors' },
  { faculty: 'Gunjan Chandwani, Narender Gautam & Meena Chaudhary', title: 'Student Performance Prediction: Leveraging Machine Learning for Educational Insights' },
  { faculty: 'Jitendra Pal Singh & Sandeep Kumar', title: 'Size and Strain Analysis of MgFe2O4 Obtained from Citric-acid Assisted Sol-gel route' },
  { faculty: 'Shruti Vashist', title: 'Renyi Fuzzy Decision Tree to Frame Fairer Tax Policies' },
  { faculty: 'Ashima Garg', title: 'An AI-Centric Multimodal Framework for Cognitive Productivity and Digital Wellbeing' },
  { faculty: 'Urmila Pilania & Manoj Kumar', title: 'Intelligent Fruit Detection using Convolution Neural Networks' },
  { faculty: 'Meena Chaudhary, Gunjan Chandwani & Narender Gautam', title: 'Dynamic Data-Driven Framework for Forecasting Employment Trends in the AI Era' },
  { faculty: 'Shanu Jain & Shelly Agarwal', title: 'Understanding the Dynamics of Group Buying Behaviour using the Motivation Opportunities-Ability Framework' },
  { faculty: 'Chandni Magoo', title: 'Performance Comparison of Machine Learning Algorithms for Depression Risk Prediction using PHQ-9 Questionnaire' },
  { faculty: 'Manoj Kumar & Urmila Pilania', title: 'Early Detection and Warning of Water-Borne Diseases using Deep Learning' },
  { faculty: 'Sunil Kumar Roy, Akanchha Singh & Yogita Sharma', title: 'Impact of Technology on Insurance Industry in Bangladesh through Bangladesh Insurance Development Project' },
  { faculty: 'Dinesh Kumar Sharma', title: 'Bio-Derived Supercapacitors for Sustainable Energy Storage Solutions' },
  { faculty: 'Jitendra Pal Singh & JaiParkash', title: 'Structural, optical and magnetic properties of zinc doped bismuth ferrite synthesized via rapid two stage solid state reaction' },
  { faculty: 'Jitendra Pal Singh & JaiParkash', title: 'Synthesis of Ni-rich layered cathodes using Sol-gel Method' },
  { faculty: 'Kavita Singh & Richa Adlakha', title: 'Dynamic Stability and Control of Load Frequency in Hybrid Power Generation Systems' },
  { faculty: 'Nitu Chauhan', title: 'Uncertainty-based Approach for Electroluminescence Image Classification of Photovoltaic Modules' },
  { faculty: 'Neha Chaudhary', title: 'Spectrum Sensing Integration and cross-layer optimisation in cognitive radio routing protocols' },
  { faculty: 'Akanksha Kathuria', title: 'A Comprehensive Bibliometric Analysis of Cultural Heritage Tourism and Sustainability Literature' },
  { faculty: 'Rashi Banerji & Akanksha Kathuria', title: 'Case Study: Cost Efficiency or Ethical Practices: Supreme Store\'s Supply Chain Transformation' },
  { faculty: 'Vandana Zutshi Bhat', title: 'Retaining the best: Employee retention in tech based MSME' },
  { faculty: 'Neeraj Chopra & Animesh Singh', title: 'Examining MOOCs Under the Microscope: Never stop learning' },
  { faculty: 'Priyanka Bansal', title: 'Design of A FCRD9T SRAM cell for Low-Power Wireless Communications' },
  { faculty: 'Priyanka Bansal & J.P. Sharma', title: 'A Review of Coverage and Multi-Robot Area Exploration Algorithms for Time-Constrained and Unknown Environments' },
  { faculty: 'Priyanka Bansal', title: 'Economic and energy comparison of fixed and tracking solar panels' },
  { faculty: 'Shweta Goel', title: 'Being Chef: Leveraging Kitchen Innovation for Sustainability and Social Impact' },
  { faculty: 'Ram Chatterjee', title: 'Fine Tuning Fake Review Detection using Feature Engineering - Feature Importance Illustrations' },
  { faculty: 'Gurpreet Singh Matharou', title: 'Comparison of Metaheuristic Algorithms with FLC using a STSMC Controller for Trajectory Tracking of Robot' },
  { faculty: 'Shiv Kumar Dixit', title: 'Effect of Different Hole Transport Layers on the Performance of Lead Free CsGeI3 based Perovskite Solar Cell' },
  { faculty: 'Bhanu Pratap Chaudhary', title: 'Analysis of CNN-LSTM assisted RIS Cooperative NOMA System' },
  { faculty: 'Bhanu Pratap Chaudhary', title: 'Optimal User Pairing Strategies for Downlink MIMO-NOMA in Rayleigh Fading Channels with Imperfect SIC Conditions' },
  { faculty: 'Bhanu Pratap Chaudhary', title: 'Comparison of Multiple Algorithms for Aerial Target Tracking Using IR Dataset in OpenCV' },
  { faculty: 'Aparna Vyas', title: 'Kannan type polynomial contractions and some fixed point theorems' },
  { faculty: 'Aparna Vyas', title: 'Extended Unique Fixed Point Theorem in Complete Quasi-Metric Space' },
  { faculty: 'Aparna Vyas', title: 'A comparative study of existing methods and the Bernoulli wavelet-based Galerkin method for solving elliptic PDEs' },
  { faculty: 'Piyush Mahendru', title: 'A Review on Scope of Surface Coating Technologies in the Electric Vehicle Sector' },
  { faculty: 'Jimmy Mehta', title: 'Flow Dynamics of Recyclable Polymers and Composites: Rheological Insights for circular economy' },
  { faculty: 'Shagun Chahal', title: 'From Headcount to skillcount: HR Analytics in Flexible Talent Strategies' },
  { faculty: 'Monika Lamba', title: 'Real-Time Groundwater Resource Evaluation Using DWLR Data and AI Models' },
  { faculty: 'Gurpreet Singh Matharou', title: 'Intelligent Battery Management Systems for Electric Vehicles using AI & ML' },
  { faculty: 'Abhishek Saxena', title: 'Intelligent Clinical Support System for Early Prediction of Cardiovascular Disease using Machine Learning' },
  { faculty: 'Meenakshi Gupta', title: 'A hybrid swarm intelligence and deep learning framework of energy-efficient routing wireless sensor networks' },
  { faculty: 'Apala Vatsa', title: 'Co Creating or Ceding Control? An Ethnographic Study of AI Co agency and Labour Precarity in India\'s Vernacular Content Creator Economy' },
  { faculty: 'Aditya Verma', title: 'Artificial Intelligence and the Changing Nature of Work: Legal Challenges in India\'s Digital Content Economy' },
  { faculty: 'Apala Vatsa', title: 'Law in Action: Experiential Legal Education for Leadership and Community Impact' },
  { faculty: 'Aditya Verma', title: 'Rethinking Legal Pedagogy in India: Experimental Learning and the Transformation of Legal Education' },
  { faculty: 'Mohit Kumar Singh', title: 'A Scheme for Joint ICI-PAPR Reduction in OCDM System without SI' },
  { faculty: 'Shalu', title: 'Empirical Study on User Sentiments: ChatGPT in India' },
  { faculty: 'Shalu', title: 'Industrial Wireless Sensor Networks Trust-Based Security Framework' },
  { faculty: 'Shalu', title: 'Holistic Analysis of Deep Learning Techniques for Disease Detection in Vegetables' },
  { faculty: 'Shalu', title: 'Effectiveness of Lazy Algorithm-Based Software Effort Estimation' },
  { faculty: 'Shalu', title: 'Multiphase Code clone detection using NSGA-II' },
  { faculty: 'Shalu', title: 'Trust Enhancement Framework for Industrial Wireless Sensor Networks' },
  { faculty: 'Akhilesh Kumar Dwivedi', title: 'Shadows of Sundarbans: Unmasking Class Conflict in Bhoma' },
  { faculty: 'Esha Khanna', title: 'Facial Expression Recognition: Current Challenges and Research Gaps' },
  { faculty: 'Chandni Magoo', title: 'Manasmitra: An Experimental Study on ML-Driven Mental Health Screening Using PHQ-9 and HRV' },
  { faculty: 'Charu Pathak', title: 'Assessing River Overflow Risk through LSTM-Based Modelling of Discharge Dynamics' },
  { faculty: 'Charu Pathak', title: 'Retinex Algorithms for Early Diagnosis of Diseases' },
  { faculty: 'Ganga Sharma', title: 'Developing Enhanced Security Protocols for Mobile Banking Applications Using MFA in Blockchain' },
  { faculty: 'Pooja Kapoor & Teena Hasija', title: 'Assessing the Impact of AI-Gamified Accounting Education on Students\' Engagement and Competence' },
  { faculty: 'Neeraj Chopra & Animesh Singh', title: 'Investigating Learner Happiness to explore behavioural intentions to continue using MOOCs' },
  { faculty: 'Sanjay Singh', title: 'Multilingual Learning in Natural Language Processing' },
  { faculty: 'Sanjay Singh', title: 'Machine Learning Techniques based AI Tools for Real-Time Monitoring of Environmental Pollution' },
  { faculty: 'Sanjay Singh', title: 'Leveraging Blockchain Technology to Improve Transparency and Efficiency in Smart City Property Transactions' },
  { faculty: 'Mira Mishra', title: 'Panchakosha Integration for Holistic Teacher Development: A Mixed-Method Study of Pre-service Teachers\' Experiences' },
  { faculty: 'Mira Mishra', title: 'Educational Technology as a Global Technoscape: Pathways to Sustainable and Inclusive Learning' },
  { faculty: 'Sahiba Sharma', title: 'Case Study: Transforming Lives: Eco-Entrepreneurship and Empowerment at Transformation Hub' },
  { faculty: 'Punam Rattan', title: 'Field-Scale Weed Classification in Rice Crops using AI-Driven Vision Models' },
  { faculty: 'Punam Rattan', title: 'Feature Selection for Fraud Detection: Improving Machine Learning Capabilities on Portable Wallet' },
  { faculty: 'Rajnesh Kumar Singh', title: 'Robotics-Enabled Manufacturing Systems for Industry 4.0 Deployment' },
  { faculty: 'Abhishek Saxena', title: 'A Review Study on the Discovery & Development of Medicine using Machine Learning' },
  { faculty: 'Meena Chaudhary', title: 'Comparative Analysis of Quantum Key Distribution Protocols and Implementation Strategies in the Post-Quantum Era' },
  { faculty: 'Shweta Goel', title: 'AI Technologies and Economic Transformation: A Systematic Review' },
  { faculty: 'Shweta Goel', title: 'Fintech as a catalyst of sustainable agricultural development' },
  { faculty: 'Minakshi Sharma', title: 'Novel hybrid approach for predicting consumer intention for sustainable packaging using machine learning techniques' },
  { faculty: 'Vani Kataria & Tanvi Dhaiya', title: 'AI in Education and Rights of Child: Examining the sufficiency of existing rights frameworks' },
  { faculty: 'Vani Kataria', title: 'A Comparative study of Secularism, Data Protection and Social conflict in Digital Age' },
  { faculty: 'Teena Hasija', title: 'Balancing Reputation and Revenue: Strategic Decision-Making in FinAsk Value under Group Insurance Vertical' },
  { faculty: 'Anup Singh Kushwaha', title: 'Beyond Unimodal Vision: A Multimodal Contrastive Learning Approach for Label-Efficient Rice Leaf Disease Detection' },
  { faculty: 'Shalu', title: 'OrganBlock: A Kidney Searching & Tracking Blockchain System' },
  { faculty: 'Shalu', title: 'A Dual-Crop Hybrid Deep Learning Pipeline for Classifying Sudden Death Syndrome in Soybean and Phytophthora Blight in Bell Pepper' },
  { faculty: 'Dinesh Tripathi', title: 'Some compact generalizations of Bernstein-type inequalities preserved by modified Smirnov operator' },
  { faculty: 'Neelu Chaudhary', title: 'Explainable Deep Sentiment Analysis: A Trustworthy AI Approach to Understanding Social Media Opinions' },
  { faculty: 'Teena Hasija', title: 'EdTech to Health Tech: Habit\'s Approach to Mitigate Pivoting and Rebranding Challenges' },
  { faculty: 'Pooja Kapoor & Teena Hasija', title: 'Future Homez: Entrepreneurial Aspirations and Operational Realities in India\'s MSME Landscape' },
  { faculty: 'Babita Yadav', title: 'Developing A Multi-Disease Risk Prediction Model Using Machine Learning' },
  { faculty: 'Jitendra Pal Singh', title: 'Radio Frequency Sputtering for Materials and Devices' },
  { faculty: 'Jitendra Pal Singh & Sandeep Kumar', title: 'Sputtering-assisted growth of Magnetic Thin Films' },
  { faculty: 'Sudhish Kumar Shukla', title: 'Gravimetric and electrochemical studies on Texas Red dye as corrosion inhibitor for mild steel' },
  { faculty: 'Roopa Rani & Arpit Sand', title: 'Ethical issues related to use of magnetic nanomaterials in plant and soil system' },
  { faculty: 'Ruchi Lal & Superna Venaik', title: 'Perceptions of Indian exporters on the role of WTO laws in shaping trade relations with foreign countries' },
  { faculty: 'Jyotsna Pandit', title: 'Digital Twin Modeling for Sustainable Water Management' },
  { faculty: 'Jyotsna Pandit', title: 'AI-Driven Groundwater Contamination Prediction Models' },
  { faculty: 'Jyotsna Pandit', title: 'Reinforcement-Based Fertigation Scheduling for Water Conservation' },
  { faculty: 'Priti Gupta', title: 'Indoor Airborne Microplastics: Sources, Human Exposure Pathways, and Health Risks' },
  { faculty: 'Priti Gupta', title: 'Introduction and Classification of Fuel energy' },
  { faculty: 'Arpit Sand', title: 'Development of a Porous Gelatin-g-Polyacrylamide Hydrogel Biosensor for Rapid Colorimetric Detection of Heavy Metals' },
  { faculty: 'Arpit Sand & Roopa Rani', title: 'History and Development of Biocomposites' },
  { faculty: 'Ruchi Gupta', title: 'A study on optimization techniques for Dijkstra\'s algorithm in wireless networks' },
  { faculty: 'Ruchi Gupta', title: 'Innovations and insights in transportation problem solving: A review from classical techniques to modern algorithms' },
  { faculty: 'Surabhi Sharma & Arushi M. Mehta', title: 'Breaking Barriers and Balancing Power: An Analysis of Women Insolvency Professionals under the IBC in India' },
  { faculty: 'Neha Chaudhary', title: 'A Transformer-based deep learning approach for fake news detection in journalism platform' },
  { faculty: 'Rashi Banerji, Animesh Singh & Savita Sharma', title: 'Beyond Compliance: Leveraging CSR for Inclusive Growth in India\'s QSR Industry' },
  { faculty: 'Khushboo Gulati', title: 'Diagnosing the role of Board Configuration and the Committees on Firm performance: A resource based Perspective' },
  { faculty: 'Sachin Lakra', title: 'Assessing the Impact of Fractal Indian Classical Music Signals on the Human Brain Using Alpha-waves from EEG' },
  { faculty: 'Sachin Lakra', title: 'A Mathematical Analysis of the Suitability of Using Fractal and Non-Fractal Patterns for Manufacturing Musical Instruments' },
  { faculty: 'Prinima Gupta', title: 'Improving Real-Time UAV Target Recognition via Super-Resolution, InceptionNeXt, and Attention-Enhanced YOLOv8' },
  { faculty: 'Surabhi Sharma', title: 'Reimagining Corporate rescue: A critical analysis of Insolvency and Bankruptcy Code in Post-pandemic India' },
  { faculty: 'Gurpreet Singh Matharou', title: 'Multi-Response Optimization of EDM Parameters for Aerospace-Grade Hybrid Metal Matrix Composites' },
  { faculty: 'Anshuman Sahai', title: 'Next-Generation Oxide-based Photovoltaics: Role of CNTs, Graphene Derivatives and Ionic Liquids in Device Engineering' },
  { faculty: 'Akanchha Singh', title: 'Harnessing Digital Communication & Social Media for Modern Workplaces' },
  { faculty: 'Meenakshi Gupta', title: 'Fetalnet 1.0: TOPSIS-guided ensemble learning with genetic feature selection and SHAP explainability for Fetal health classification' },
  { faculty: 'Vinayak Vandan Pathak', title: 'Component analysis and temporal evaluation of water quality in the Yamuna River' },
  { faculty: 'Minakshi Sharma, Ankita & Pragati', title: 'A Hand to Hold: Challenges of Bringing PCOD care to women' },
  { faculty: 'Sachin Lakra', title: 'Green Technology and the Energy Complexity of an Algorithm' },
]

export const communicatedPapers: Publication[] = [
  { faculty: 'Akanksha Kathuria', title: 'AI Governance and Ethical Implications in Talent Management: Balancing Innovation and Integrity' },
  { faculty: 'Akanksha Kathuria', title: 'The Synergy of Sustainable and Emerging Technologies: Future Perspectives' },
  { faculty: 'Garima Pahwa', title: 'Legal Empowerment of Indigenous People: Assessing Property Rights under Forest Rights Act, 2006 and PESA' },
  { faculty: 'Akanksha Kathuria', title: 'AI-Enabled Learning in Marginalized Contexts: Rethinking Access and Inclusion in Rural Education' },
  { faculty: 'Akanchha Singh', title: 'Rethinking Performance Management for Talent Retention: The Mediating Role of Rewards, Recognition, and Engagement' },
  { faculty: 'Pooja Kapoor', title: 'Understanding the Relationship between ESG and Financial Distress: Perspectives from Indian Stock Market' },
  { faculty: 'Animesh Singh & Rashi Banerji', title: 'Ethical Leadership and Happiness at Work as Predictors of Organisational Citizenship Behaviour' },
  { faculty: 'Akanksha Kathuria', title: 'Digital Transformation in Engineering Consulting: A Case Study of Apex Consultants' },
  { faculty: 'Akanchha Singh', title: 'Organizational Commitment and Moonlighting Intentions in South Asian Healthcare' },
  { faculty: 'Piyush Mahendru', title: 'Multi-Criteria Decision making for selecting optimal composition under Erosive Environment Using Entropy-TOPSIS Approach' },
  { faculty: 'Jaiparkash & Jitendra Pal Singh', title: 'Li doping induced electrochemical energy storage modulation in MgTiO3 nano crystals for aqueous symmetric supercapacitors' },
  { faculty: 'Jitendra Pal Singh', title: 'Ion Irradiation in Emerging Materials and Devices' },
  { faculty: 'Jitendra Pal Singh', title: 'Ion irradiation in magnetic oxides' },
  { faculty: 'Jitendra Pal Singh & Sandeep Kumar', title: 'AI/ML in designing materials for Spintronics applications' },
  { faculty: 'Rajnesh Kumar Singh', title: 'Dinov2-Enhanced Multi-Modal Framework with Yolov10 for Real World Underwater Object Detection' },
  { faculty: 'Rajnesh Kumar Singh', title: 'An Ultrathin Graphite Based Absorber For Wearable application' },
  { faculty: 'Jitendra Pal Singh & Sudhish Kumar Shukla', title: 'Next-Generation Zinc-Air Batteries: Anode Materials & Design Breakthroughs' },
  { faculty: 'Jitendra Pal Singh', title: 'Enhancing Performance and Efficiency of Solid State Batteries using AI/ML Approaches' },
  { faculty: 'Jitendra Pal Singh & JaiParkash', title: 'Spectroscopic and magnetic studies of 0.9Bi0.80Sr0.20FeO3-0.1CoFe2O4 composite' },
  { faculty: 'Jitendra Pal Singh & JaiParkash', title: 'Advances in Mg-based Spinel-structured Materials for Energy Storage Application' },
  { faculty: 'Aaratrika Pandey', title: 'Smart City Surveillance and Parental Responsibilities' },
  { faculty: 'Aaratrika Pandey', title: 'Surveillance Shadows: Gender-Based Violence, Privacy Erosion, and Endangerment to Women and Marginalized Genders' },
  { faculty: 'Jitendra Pal Singh', title: 'Extended X-ray Absorption Fine Structure Spectrum of LiNi1/3Co1/3Mn1/3O2 Single Particle' },
  { faculty: 'Jitendra Pal Singh & Sudhish Kumar Shukla', title: 'Investigation of Zinc Air Rechargeable Batteries using Synchrotron X-rays' },
  { faculty: 'Jitendra Pal Singh', title: 'Starch-Stabilized Zinc Oxide via Mentha piperita Extract: A Pathway to Sustainable Energy Storage' },
  { faculty: 'Jitendra Pal Singh & Moditma', title: 'Sputtering of Lithium Lanthanum Zirconate on Quartz substrate' },
  { faculty: 'Akanksha Kathuria', title: 'Avatar Economy in Retail: A Case Study of Reliance Retail' },
  { faculty: 'Akanksha Kathuria', title: 'A Hybrid Deep Learning Framework for Stress and Behavioral Pattern Recognition' },
  { faculty: 'Minakshi Sharma & Pragati', title: 'A Hand to Hold: Challenges of Bringing PCOD care to women' },
  { faculty: 'Sahiba Sharma', title: 'Mitigating the effect of global trade disruption on Customer Satisfaction in the age of Artificial Intelligence' },
  { faculty: 'Sahiba Sharma', title: 'A Bibliometric analysis of the Antecedents of Sales Performance using VOSviewer' },
  { faculty: 'Jitendra Pal Singh', title: 'SEI/CEI Interphases and Internal Resistance Evolution in EV Batteries: Implications for BMS, Safety, and Fast Charging' },
  { faculty: 'Gianender Kajal', title: 'TiO2 Photocatalytic Nano coatings on Banana and Bamboo Fabrics: Comparative Study on Self-Cleaning Efficiency' },
  { faculty: 'Shagun Chahal', title: 'Fresh Beginnings, Complex Choices: Drinkcarts\' Growth Dilemma' },
  { faculty: 'Akanchha Singh', title: 'Workplace spirituality, organizational commitment and faculty well-being: A relational governance perspective' },
  { faculty: 'Abhishek Saxena', title: 'Wearables for Stress Detection utilizing Temporally-Aware Adaptive Graph Convolutional Network' },
  { faculty: 'Pooja Parmar', title: 'A comprehensive exploration of molecular aspects of Rice-Ustilaginoidea virens interactions' },
  { faculty: 'Garima Pahwa', title: 'Comparative Analysis between Dayak And Bhil communities' },
  { faculty: 'Sahiba Sharma', title: 'Technostress and Employee Performance in Virtual Teams: A Systematic Literature Review' },
  { faculty: 'Prinima Gupta', title: 'Improving Real-Time UAV Target Recognition via Super-Resolution, InceptionNeXt, and Attention-Enhanced YOLOv8' },
  { faculty: 'Meenakshi Gupta', title: 'Early CKD Detection using Hybrid Ensemble Models with GWO Optimization and XGBoost-Based Imputation' },
  { faculty: 'Neeraj Chopra, Akanksha Kathuria, Minakshi Sharma & Vandana Zutshi Bhat', title: 'Successful diffusion of AI in supply chains: An analysis of enablers and inhibitors using MCDM approach' },
  { faculty: 'Minakshi Sharma', title: 'The Fusion of Play and Personalization: Examining the Efficacy of Gamification and AI-Driven Learning Paths' },
  { faculty: 'Minakshi Sharma', title: 'Peaks, Purity, and Profits: Kimalaya Naturals\' Himalayan Scaling Challenge' },
  { faculty: 'Shalu', title: 'Performance Analysis of Classification Models for Breast Cancer Prediction on the Wisconsin Diagnostic Dataset' },
  { faculty: 'Shalu', title: 'Zero Trust-Based Trust Score Paradigm to Cloud Based Wireless Sensor Network' },
  { faculty: 'Shalu', title: 'Speech Emotion Detection using Machine learning' },
  { faculty: 'Abhishek Saxena', title: 'Predictive Modelling of Clean Water Supply in Riau Province: A Deep Learning Approach' },
  { faculty: 'Abhishek Saxena', title: 'A Nature-Inspired Biometric Cryptography Framework for Secure and Reproducible Fingerprint-Based Authentication' },
  { faculty: 'Abhishek Saxena', title: 'AgriProdNet: A Framework for Predicting Agricultural Productivity Factors Using Agro Climatic Data' },
  { faculty: 'Deepti Thakral', title: 'A Multi-Task Deep Learning Framework for Joint Prediction of Productivity and Stress from Smartphone Usage Patterns' },
  { faculty: 'Deepti Thakral', title: 'Graph-Enhanced Swarm Optimized Ensemble Learning for Heart Disease Prediction' },
  { faculty: 'Prinima Gupta', title: 'Optimizing Undergraduate Engineering Admission decisions through PCA and K-Fold Cross-Validation' },
  { faculty: 'Sahiba Sharma', title: 'Case Study: Trust Built Over Time, Tested in Crisis: A Case of Anurag Trading Company' },
  { faculty: 'Kushal Lalwani', title: 'Dynamics of green competitiveness and export performance under climate policy constraints' },
  { faculty: 'Asmita Patel', title: 'Shaping Legal Framework To Address Public Health Emergencies: Global Norms and the Case of India' },
  { faculty: 'Animesh Singh', title: 'An Empirical Investigation On Relationship Between Organizational Learning Capabilities And OCB' },
  { faculty: 'Animesh Singh', title: 'Identify Factors Of Hedonic And Utilitarian Gratification Gained From Ephemeral Content On Social Media' },
  { faculty: 'Rajnesh Kumar Singh', title: 'Enhanced Robotic Motion Planning: A Hybrid Approach Combining Reactive Control and Genetic Algorithms' },
  { faculty: 'Meenakshi Gupta', title: 'Scheduling-Aware Outage Analysis for UAV-Enabled Mixed RF/FSO Multi-User Networks' },
  { faculty: 'Meenakshi Gupta', title: 'Self-Stabilizing Spoon for Parkinson\'s Patients: A Review of Current Technologies and a Low-Cost Design Methodology' },
  { faculty: 'Neelu Chaudhary', title: 'A Hybrid Machine Learning Framework for Predicting Differentiated Thyroid Cancer Recurrence' },
  { faculty: 'Roopa Rani', title: 'Utilization of agricultural waste-derived biochar for the removal of Phosphorus from wastewater' },
  { faculty: 'Roopa Rani', title: 'In vitro antimicrobial activity of Iron Nanoparticle synthesized using Lotus seed coats' },
  { faculty: 'Ankita Gaur', title: 'Multi-Criteria Mamdani Fuzzy Inference Modeling of Climate-Induced Yield Variability in Indian Staple Crops' },
  { faculty: 'Ankita Gaur', title: 'Enhancing student creativity through artificial intelligence tools in higher education: An empirical study' },
  { faculty: 'Ankita Gaur', title: 'Mathematical Dimensions of Artificial Intelligence' },
  { faculty: 'Bhawna Singla', title: 'Alternative Ratio and Product Type Exponential Estimators Using Simple Random Sampling and Double Sampling' },
  { faculty: 'Seema Aggarwal', title: 'Interpretable recurrent neural networks for modelling temporal dynamics of acquired drug resistance in targeted therapy' },
  { faculty: 'Anupam Sharma', title: 'Legal Implications of AI in Agriculture: A Systematic Review on Farmer Protection and Fairness' },
  { faculty: 'Anupam Sharma', title: 'From Regulation to Resistance: A Socio-Legal Perspective on Cryptocurrency and Social Stratification in India' },
  { faculty: 'Sharv Datt Anand', title: 'Digital Inclusion and Equity for Children with Learning Disabilities' },
  { faculty: 'Sharv Datt Anand', title: 'AI for Social Good' },
  { faculty: 'A. Jayamani', title: 'Quantum Sensing in Healthcare: Enhancing Diagnostics, Monitoring, and Treatment Precision' },
  { faculty: 'A. Jayamani', title: 'N-heterocyclic imidazolium carbene-platinum(II) complexes: Exploring reactivity, computational analysis, and DNA/BSA interactions' },
  { faculty: 'A. Jayamani', title: 'Photo-Responsive Nickel(II) complex with enhanced anticancer activity: Insights into biomolecular interaction' },
  { faculty: 'Pooja Kapoor', title: 'Bridging the Digital Divide in Higher Education: A Systematic Review of Gender Disparities in FinTech Adoption' },
  { faculty: 'Ruchi Gupta', title: 'Understanding socio-political instability through nonlinear dynamics: A Lorenz-type model' },
  { faculty: 'Mohit Kumar Singh', title: 'Blind SLM & PTS Schemes using Concentric Diamond Mapping for PAPR Reduction in AFDM System' },
  { faculty: 'Mohit Kumar Singh', title: 'Performance Evaluation of Symbol Repetition Based ICI Cancellation Schemes in AFDM System' },
  { faculty: 'Vandana Zutshi Bhat & Rashi Banerji', title: 'Smart Supply Chains for Smarter EVs: Real-Time Visibility, Optimization, and Decision-Making in Mahindra Electric Supply Chain' },
  { faculty: 'Shalu', title: 'ATREW: Adaptive Trust and Reliability Enhancement Framework for Wireless Sensor Networks' },
  { faculty: 'Shalu', title: 'Human Chronic Disease Classification Using an Intelligent Healthcare System Based on IoB' },
  { faculty: 'Shalu', title: 'Optimization of T-T models using ADAM-TT-IDS and H-ADAM-ANT-TTIDS Algorithms for Robust Enhancement of IDS' },
  { faculty: 'Jitendra Pal Singh & Moditma', title: 'Mechanistic Investigations on the Annealing Induced Diffusion and Crystallization in Lithium Lanthanum Zirconate Thin Films' },
  { faculty: 'Rashee Singh', title: 'A study of effect of Emotional Intelligence, Adult Attachment Styles and Psychological resilience level on Marital Success' },
  { faculty: 'Chaitali Wadhwa', title: 'Intersecting Law and Labour: A Comparative Analysis of Maternity Benefit Policies in India and Sri Lanka' },
  { faculty: 'Chaitali Wadhwa', title: 'Motherhood And The Right To Education: Harmonising Statutory Entitlements And Institutional Practice' },
  { faculty: 'Chaitali Wadhwa', title: 'Advancing Recruitment Equity using AI solutions to combat Motherhood Discrimination in the workplace' },
  { faculty: 'Pooja Sachdeva', title: 'Design and Development of an AI stabilized foot mounted propulsion system for modular personal flying shoes' },
  { faculty: 'Pooja Sachdeva', title: 'Multimodal Nanorobotic Framework for Non-Invasive Lysis of Paraganglioma: The "Inject and Done" Model' },
  { faculty: 'Jitendra Pal Singh & Sandeep Kumar', title: 'Growth Perspective, Applications and Advanced Characterisation Strategies for Spinel Magnetic Oxide Nanostructures' },
  { faculty: 'Sunil K. Roy & Unmesh Shukla', title: 'Does the culture as context paradigm hold in knowledge intensive organization' },
  { faculty: 'Shweta Goel', title: 'Navigating the Landscape of Sustainable and Impact-Driven Finance for a Greener Tomorrow' },
  { faculty: 'Jitendra Pal Singh', title: 'Polarization Enabled Surface Enhanced Polyurethane Composite based All-in-One Flexible Electrode with Improved EDLC Behaviour' },
]
